// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '[GEMINI_API_KEY_REMOVED]',
    appId: '1:876460230034:web:4e112e943b6e7d5cb56d4b',
    messagingSenderId: '876460230034',
    projectId: 'skyaware-8b2e8',
    authDomain: 'skyaware-8b2e8.firebaseapp.com',
    storageBucket: 'skyaware-8b2e8.firebasestorage.app',
    measurementId: 'G-5J5767LLX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwC3fF2osR7GtAuXR529-qDvnyt4NETu0',
    appId: '1:876460230034:android:f1a8f1f0d7e7b270b56d4b',
    messagingSenderId: '876460230034',
    projectId: 'skyaware-8b2e8',
    databaseURL: 'https://skyaware-8b2e8-default-rtdb.firebaseio.com',
    storageBucket: 'skyaware-8b2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBES_x7bCHL_1hy0iwElgOZNINMnZwaJ5c',
    appId: '1:876460230034:ios:9144443cd11c938db56d4b',
    messagingSenderId: '876460230034',
    projectId: 'skyaware-8b2e8',
    databaseURL: 'https://skyaware-8b2e8-default-rtdb.firebaseio.com',
    storageBucket: 'skyaware-8b2e8.firebasestorage.app',
    androidClientId: '876460230034-485q4b3rvcf92e3ojar14hjcajieu2v7.apps.googleusercontent.com',
    iosClientId: '876460230034-sto5k06b1hv2nb67ai35lm2lk12dceuf.apps.googleusercontent.com',
    iosBundleId: 'com.andy.skyaware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '[GEMINI_API_KEY_REMOVED]',
    appId: '1:876460230034:ios:90530893369e3eeab56d4b',
    messagingSenderId: '876460230034',
    projectId: 'skyaware-8b2e8',
    storageBucket: 'skyaware-8b2e8.firebasestorage.app',
    androidClientId: '876460230034-485q4b3rvcf92e3ojar14hjcajieu2v7.apps.googleusercontent.com',
    iosClientId: '876460230034-lth7av2d4l50ncdhqn62pjcfnli2gah6.apps.googleusercontent.com',
    iosBundleId: 'com.example.skyaware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '[GEMINI_API_KEY_REMOVED]',
    appId: '1:876460230034:web:fa90cfba91064c18b56d4b',
    messagingSenderId: '876460230034',
    projectId: 'skyaware-8b2e8',
    authDomain: 'skyaware-8b2e8.firebaseapp.com',
    storageBucket: 'skyaware-8b2e8.firebasestorage.app',
    measurementId: 'G-9B35GW0BZB',
  );

}